- name: Running SB Starter app remotely at Azure VMs
  hosts: azhosts
  tasks:
    - name: What is my ip
      ignore_errors: yes
      shell: "curl ifconfig.me"
      register: curl1

    - debug: var=curl1.stdout_lines

    - name: Retrieving all PIDs of running java process
      ignore_errors: yes
      shell: "ps -few | grep java | awk '{print $2}'"
      register: running_processes

    - name: Killing running the processes
      ignore_errors: yes
      shell: "kill -9 {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"

    - name: Starting up the Spring Boot app
      ignore_errors: no
      shell: "nohup java -jar /mnt/share01/target/spring-boot-initial-0.0.1-SNAPSHOT.jar > initial.log 2>&1 &"