version: '2'

services:
  config-server:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-config-server:latest
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-discovery-server:latest
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
     - config-server
    # entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761

  customers-service:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-customers-service:latest
    container_name: customers-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    # entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8081:8081

  visits-service:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-visits-service:latest
    container_name: visits-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    # entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8082:8082

  vets-service:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-vets-service:latest
    container_name: vets-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    # entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083

  api-gateway:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-api-gateway:latest
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    # entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080

  tracing-server:
    image: acrusw001.azurecr.io/openzipkin/zipkin:latest
    container_name: tracing-server
    mem_limit: 512M
    ports:
     - 9411:9411
    # environment:
    # - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom

  admin-server:
    image: acrusw001.azurecr.io/springcommunity/spring-petclinic-admin-server:latest
    container_name: admin-server
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    # entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090

  ## Grafana / Prometheus

  grafana-server:
    image: acrusw001.azurecr.io/spring-petclinic-microservices_grafana-server:latest
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    image: acrusw001.azurecr.io/spring-petclinic-microservices_prometheus-server:latest
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090
